language: python
python:
  - "2.7"
  - "3.3"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run -m unittest discover -s tests/
after_success:
  - codecov
sudo: false
cache: pip
